name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set dynamic tag
        id: vars
        run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag dentistry-kcdi:${{ env.TAG }}

      - name: Tag the Docker image
        run: |
          docker tag dentistry-kcdi:$(date +%s) markyvva/dentistry-kcdi:latest
          docker tag dentistry-kcdi:$(date +%s) markyvva/dentistry-kcdi:${{ env.TAG }}

      - name: Push the Docker image
        run: |
          docker push markyvva/dentistry-kcdi:latest
          docker push markyvva/dentistry-kcdi:${{ env.TAG }}
